version: '3.7'
services:
  postgresql:
    image: postgres:15.0
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sampledb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
