-- 加盟店企業テーブル
CREATE TABLE AFFILIATE_COMPANY (
    AFFILIATE_COMPANY_CODE SERIAL PRIMARY KEY,
    AFFILIATE_COMPANY_NAME VARCHAR(255) NOT NULL,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE
);

-- 店舗テーブル
CREATE TABLE STORE (
    AFFILIATE_COMPANY_CODE INT REFERENCES AFFILIATE_COMPANY(AFFILIATE_COMPANY_CODE),
    STORE_CODE SERIAL PRIMARY KEY,
    STORE_NAME VARCHAR(255) NOT NULL,
    LOCATION TEXT
);

-- 会員テーブル
CREATE TABLE MEMBER (
    MEMBER_CODE SERIAL PRIMARY KEY,
    MEMBER_NAME VARCHAR(255) NOT NULL,
    JOIN_DATE DATE,
    ADDRESS TEXT,
    GENDER VARCHAR(10),
    DATE_OF_BIRTH DATE,
    POINT_BALANCE INT
);

-- 加盟企業商品テーブル
CREATE TABLE AFFILIATE_PRODUCT (
    AFFILIATE_COMPANY_CODE INT REFERENCES AFFILIATE_COMPANY(AFFILIATE_COMPANY_CODE),
    AFFILIATE_PRODUCT_CODE SERIAL PRIMARY KEY,
    CROSS_ANALYSIS_PRODUCT_CODE INT,
    AFFILIATE_PRODUCT_NAME VARCHAR(255) NOT NULL,
    JAN_CODE VARCHAR(50)
);

-- 横断分析用商品情報テーブル
CREATE TABLE CROSS_ANALYSIS_PRODUCT (
    CROSS_ANALYSIS_PRODUCT_CODE SERIAL PRIMARY KEY,
    CROSS_ANALYSIS_PRODUCT_NAME VARCHAR(255) NOT NULL
);

-- 支払テーブル
CREATE TABLE PAYMENT (
    RECEIPT_NUMBER SERIAL PRIMARY KEY,
    MEMBER_CODE INT REFERENCES MEMBER(MEMBER_CODE),
    AFFILIATE_COMPANY_CODE INT REFERENCES AFFILIATE_COMPANY(AFFILIATE_COMPANY_CODE),
    STORE_CODE INT REFERENCES STORE(STORE_CODE),
    PAYMENT_DATE_TIME TIMESTAMP,
    USED_POINT INT
);

-- 支払方法明細テーブル
CREATE TABLE PAYMENT_METHOD_DETAIL (
    RECEIPT_NUMBER INT REFERENCES PAYMENT(RECEIPT_NUMBER),
    PAYMENT_METHOD_CODE INT,
    PAYMENT_AMOUNT INT,
    GIVEN_POINT INT
);

-- 購入商品明細テーブル
CREATE TABLE PURCHASE_PRODUCT_DETAIL (
    RECEIPT_NUMBER INT REFERENCES PAYMENT(RECEIPT_NUMBER),
    AFFILIATE_COMPANY_CODE INT REFERENCES AFFILIATE_COMPANY(AFFILIATE_COMPANY_CODE),
    AFFILIATE_PRODUCT_CODE INT REFERENCES AFFILIATE_PRODUCT(AFFILIATE_PRODUCT_CODE),
    PURCHASE_COUNT INT,
    PRODUCT_UNIT_PRICE INT,
    GIVEN_POINT INT
);

-- 支払方法テーブル
CREATE TABLE PAYMENT_METHOD (
    PAYMENT_METHOD_CODE SERIAL PRIMARY KEY,
    PAYMENT_METHOD_NAME VARCHAR(255) NOT NULL,
    POINT_SETTING_CODE INT
);

-- ポイント設定テーブル
CREATE TABLE POINT_SETTING (
    POINT_SETTING_CODE SERIAL PRIMARY KEY,
    APPLICABLE_START_DATE DATE,
    APPLICABLE_END_DATE DATE,
    POINT_RATE FLOAT
);

-- クーポン設定テーブル
CREATE TABLE COUPON_SETTING (
    COUPON_CODE SERIAL PRIMARY KEY,
    COUPON_NAME VARCHAR(255) NOT NULL,
    PLANNING_AFFILIATE_COMPANY_CODE INT REFERENCES AFFILIATE_COMPANY(AFFILIATE_COMPANY_CODE),
    DISTRIBUTION_START_DATE DATE,
    DISTRIBUTION_END_DATE DATE,
    USAGE_START_DATE DATE,
    USAGE_END_DATE DATE,
    POINT_RATE FLOAT,
    DISTRIBUTION_LIMIT INT
);

-- クーポン設定対象店舗テーブル
CREATE TABLE COUPON_TARGET_STORE (
    COUPON_CODE INT REFERENCES COUPON_SETTING(COUPON_CODE),
    AFFILIATE_COMPANY_CODE INT REFERENCES AFFILIATE_COMPANY(AFFILIATE_COMPANY_CODE),
    STORE_CODE INT REFERENCES STORE(STORE_CODE)
);

-- クーポン設定対象商品テーブル
CREATE TABLE COUPON_TARGET_PRODUCT (
    COUPON_CODE INT REFERENCES COUPON_SETTING(COUPON_CODE),
    AFFILIATE_COMPANY_CODE INT REFERENCES AFFILIATE_COMPANY(AFFILIATE_COMPANY_CODE),
    AFFILIATE_PRODUCT_CODE INT REFERENCES AFFILIATE_PRODUCT(AFFILIATE_PRODUCT_CODE)
);

-- クーポン配布テーブル
CREATE TABLE COUPON_DISTRIBUTION (
    COUPON_CODE INT REFERENCES COUPON_SETTING(COUPON_CODE),
    MEMBER_CODE INT REFERENCES MEMBER(MEMBER_CODE),
    DISTRIBUTED_FLAG BOOLEAN,
    DISTRIBUTION_DATE_TIME TIMESTAMP
);

-- クーポン利用テーブル
CREATE TABLE COUPON_USAGE (
    COUPON_CODE INT REFERENCES COUPON_SETTING(COUPON_CODE),
    RECEIPT_NUMBER INT REFERENCES PAYMENT(RECEIPT_NUMBER)
);
